# Generated by Django 3.1.2 on 2020-11-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_dir', models.CharField(max_length=20, verbose_name='ФИО')),
                ('login_dir', models.CharField(max_length=20, verbose_name='Логин')),
                ('password_dir', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='DocMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpz_accept', models.CharField(max_length=20, verbose_name='Выполнено')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tz_link', models.SlugField(max_length=200, verbose_name='Сылка на ТЗ')),
                ('ptz_link', models.SlugField(max_length=200, verbose_name='Сылка на РПЗ')),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.SlugField(max_length=200, verbose_name='Сылка')),
            ],
        ),
        migrations.CreateModel(
            name='RealisationMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_done', models.IntegerField(max_length=3, verbose_name='Процент готовности')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_stud', models.CharField(max_length=20, verbose_name='ФИО')),
                ('login_stud', models.CharField(max_length=20, verbose_name='Логин')),
                ('password_stud', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_work', models.CharField(max_length=20, verbose_name='Название работы')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_accept', models.CharField(max_length=20, verbose_name='Состояние работы')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_work', models.IntegerField(max_length=6, verbose_name='Номер работы')),
                ('id_stud', models.IntegerField(max_length=6, verbose_name='Номер студента')),
                ('subject', models.CharField(max_length=20, verbose_name='Дисциплина')),
                ('type', models.CharField(max_length=20, verbose_name='Тип работы')),
            ],
        ),
    ]
