# Generated by Django 3.1.2 on 2020-11-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='id_dir',
            field=models.ManyToManyField(to='StudWorkApp.Work'),
        ),
        migrations.AddField(
            model_name='docmark',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
        migrations.AddField(
            model_name='realisationmark',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_stud',
            field=models.ManyToManyField(to='StudWorkApp.Work'),
        ),
        migrations.AddField(
            model_name='topic',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
        migrations.AddField(
            model_name='topicaccept',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
        migrations.AddField(
            model_name='work',
            name='id_dir',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер руководителя'),
        ),
        migrations.AlterField(
            model_name='realisationmark',
            name='percent_done',
            field=models.IntegerField(verbose_name='Процент готовности'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password_stud',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id_stud',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Номер студента'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id_work',
            field=models.IntegerField(default=0, verbose_name='Номер работы'),
        ),
    ]
