# Generated by Django 3.1.2 on 2020-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0002_auto_20201102_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.RemoveField(
            model_name='director',
            name='id_dir',
        ),
        migrations.AddField(
            model_name='director',
            name='id_dir',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_stud',
        ),
        migrations.AddField(
            model_name='student',
            name='id_stud',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
