# Generated by Django 3.1.2 on 2020-11-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0003_auto_20201102_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docmark',
            options={'verbose_name': 'Состояние работы', 'verbose_name_plural': 'Состояние работ'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'verbose_name': 'Документация', 'verbose_name_plural': 'Документация'},
        ),
        migrations.AlterModelOptions(
            name='realisation',
            options={'verbose_name': 'Сылка на github', 'verbose_name_plural': 'Сылки на github'},
        ),
        migrations.AlterModelOptions(
            name='realisationmark',
            options={'verbose_name': 'Процент выполнения', 'verbose_name_plural': 'Процент выполнения'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='topicaccept',
            options={'verbose_name': 'Состояние темы', 'verbose_name_plural': 'Состояние тем'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
        migrations.RemoveField(
            model_name='director',
            name='id',
        ),
        migrations.RemoveField(
            model_name='docmark',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='realisationmark',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='topicaccept',
            name='id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='id_dir',
        ),
        migrations.RemoveField(
            model_name='work',
            name='id_stud',
        ),
        migrations.AlterField(
            model_name='director',
            name='id_dir',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='docmark',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='ptz_link',
            field=models.URLField(verbose_name='Сылка на РПЗ'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='tz_link',
            field=models.URLField(verbose_name='Сылка на ТЗ'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='github',
            field=models.URLField(verbose_name='Сылка на github'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='realisationmark',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_stud',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_work',
            field=models.CharField(max_length=20, verbose_name='Тема работы'),
        ),
        migrations.AlterField(
            model_name='topicaccept',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='topicaccept',
            name='topic_accept',
            field=models.CharField(max_length=20, verbose_name='Тема утверждена'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id_work',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
    ]
