# Generated by Django 3.1.2 on 2020-11-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0004_auto_20201103_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='id_dir',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='docmark',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='realisationmark',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_stud',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='topicaccept',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='id_work',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер работы'),
        ),
    ]
