# Generated by Django 3.1.2 on 2020-11-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0006_auto_20201103_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.work'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_work',
            field=models.CharField(default='Тема не выбрана', max_length=20, verbose_name='Тема работы'),
        ),
    ]
