# Generated by Django 3.1.2 on 2020-11-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0007_auto_20201103_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.work'),
        ),
        migrations.AlterField(
            model_name='realisationmark',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.realisation'),
        ),
        migrations.AlterField(
            model_name='topicaccept',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.topic'),
        ),
    ]
