# Generated by Django 3.1.2 on 2020-11-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0008_auto_20201103_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='id_dir',
            field=models.ManyToManyField(to='StudWorkApp.Director'),
        ),
        migrations.AddField(
            model_name='work',
            name='id_stud',
            field=models.ManyToManyField(to='StudWorkApp.Student'),
        ),
    ]
