# Generated by Django 3.1.2 on 2020-11-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0009_auto_20201103_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fio_dir',
            field=models.CharField(max_length=40, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fio_stud',
            field=models.CharField(max_length=40, verbose_name='ФИО'),
        ),
    ]
