# Generated by Django 3.1.2 on 2020-11-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0010_auto_20201103_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmark',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.documentation'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.work'),
        ),
    ]
