# Generated by Django 3.1.2 on 2020-11-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0013_auto_20201104_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='id_dir',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_stud',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
