# Generated by Django 3.1.2 on 2020-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0014_auto_20201104_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='id_dir',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_stud',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
