# Generated by Django 3.1.2 on 2020-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0016_auto_20201104_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmark',
            name='rpz_accept',
            field=models.CharField(default='Нет', max_length=20, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='realisationmark',
            name='percent_done',
            field=models.IntegerField(default=0, verbose_name='Процент готовности'),
        ),
        migrations.AlterField(
            model_name='topicaccept',
            name='topic_accept',
            field=models.CharField(default='Не утверждено', max_length=20, verbose_name='Тема утверждена'),
        ),
    ]
