# Generated by Django 3.1.2 on 2020-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0017_auto_20201105_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_work',
            field=models.CharField(default='Тема не выбрана', max_length=60, verbose_name='Тема работы'),
        ),
    ]
