# Generated by Django 3.1.2 on 2020-11-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0018_auto_20201105_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='ptz_link',
            field=models.URLField(blank=True, verbose_name='Сылка на РПЗ'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='tz_link',
            field=models.URLField(blank=True, verbose_name='Сылка на ТЗ'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='github',
            field=models.URLField(blank=True, verbose_name='Сылка на github'),
        ),
    ]
