# Generated by Django 3.1.2 on 2020-11-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudWorkApp', '0020_auto_20201106_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmark',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.documentation'),
        ),
        migrations.AlterField(
            model_name='realisationmark',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.realisation'),
        ),
        migrations.AlterField(
            model_name='topicaccept',
            name='id_work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='StudWorkApp.topic'),
        ),
    ]
